# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.


entries:
- title: Sidebar
  product: Stat Mech 101
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage
      output: pdf
      type: frontmatter

  - title: Introduction
    output: web, pdf
    folderitems:
    - title: About Stat Mech 101
      url: /p1_landing_page.html
      output: web

    - title: Prologue
      url: /p1_sample1.html
      output: web, pdf

  - title: Basics
    output: web, pdf

    folderitems:
    - title: Microstates meet Macrostates
      url: /p1_sample2.html
      output: web, pdf

    - title: Boltzmann Entropy
      url: /p1_sample3.html
      output: web, pdf

    - title: Shannon Entropy
      url: /p1_sample4.html
      output: web, pdf

  - title: Applications
    output: web, pdf

    folderitems:
    - title: Boltzmann distribution
      url: /p1_sample5.html
      output: web, pdf

      url: /p1_sample7.html
      output: web, pdf
